# this file got generated by chatgpt on 4th of september 2026 with the 
# follwing prompts: 
# program a python script:
# - input from pure data (1 text message, 1 slider)
# - send via OSC
# - use osc4py3 (https://osc4py3.readthedocs.io/en/latest/)
# - the data should be displayed on a 128x32 oled display on a raspberry pi5
# - the script should be based on this example: https://github.com/adafruit/Adafruit_CircuitPython_SSD1306/blob/main/examples/ssd1306_stats.py
# - first line shows text message, second line shows a rectangle as a slider (pure data sends data between 0 and 1)

#!/usr/bin/env python3

import time

import busio
from board import SCL, SDA
from PIL import Image, ImageDraw, ImageFont
import adafruit_ssd1306

from osc4py3.as_eventloop import (
    osc_startup,
    osc_udp_server,
    osc_method,
    osc_process,
    osc_terminate,
)


# ============================================================
# SETTINGS
# ============================================================

OLED_WIDTH = 128
OLED_HEIGHT = 32

OSC_HOST = "127.0.0.1"
OSC_PORT = 8000

TEXT_ADDRESS = "/text"
SLIDER_ADDRESS = "/slider"

# Text scrolling
MAX_TEXT_CHARS = 21
SCROLL_INTERVAL = 0.20

# Main loop sleep
LOOP_SLEEP = 0.005


# ============================================================
# GLOBAL STATE
# ============================================================

text_message = ""

# Full OSC slider value: 0.0 ... 1.0
slider_value = 0.0

# Last slider position actually displayed
last_slider_pixel = -1

# Last text displayed
last_display_text = ""

# Text scrolling
scroll_position = 0
last_scroll_time = time.monotonic()


# ============================================================
# OLED INITIALIZATION
# ============================================================

print("Starting OLED...")

i2c = busio.I2C(SCL, SDA)

display = adafruit_ssd1306.SSD1306_I2C(
    OLED_WIDTH,
    OLED_HEIGHT,
    i2c
)

display.fill(0)
display.show()

image = Image.new(
    "1",
    (OLED_WIDTH, OLED_HEIGHT)
)

draw = ImageDraw.Draw(image)

font = ImageFont.load_default()

print("OLED ready.")


# ============================================================
# GET TEXT FOR DISPLAY
# ============================================================

def get_display_text():

    if len(text_message) <= MAX_TEXT_CHARS:
        return text_message

    scrolling_text = text_message + "     " + text_message

    start = scroll_position
    end = start + MAX_TEXT_CHARS

    return scrolling_text[start:end]


# ============================================================
# UPDATE OLED
# ============================================================

def update_display():

    global last_display_text
    global last_slider_pixel

    display_text = get_display_text()

    # Convert full 0.0...1.0 value to OLED pixels.
    #
    # The OSC value itself is NOT rounded.
    slider_pixel = round(slider_value * 122)

    # Remember what we're displaying.
    last_display_text = display_text
    last_slider_pixel = slider_pixel

    # Clear framebuffer.
    draw.rectangle(
        (0, 0, OLED_WIDTH - 1, OLED_HEIGHT - 1),
        fill=0
    )

    # --------------------------------------------------------
    # TEXT
    # --------------------------------------------------------

    draw.text(
        (0, 0),
        display_text,
        font=font,
        fill=255
    )

    # --------------------------------------------------------
    # SLIDER
    # --------------------------------------------------------

    slider_x = 2
    slider_y = 17
    slider_width = 124
    slider_height = 12

    # Slider outline.
    draw.rectangle(
        (
            slider_x,
            slider_y,
            slider_x + slider_width,
            slider_y + slider_height
        ),
        outline=255,
        fill=0
    )

    # Slider fill.
    if slider_pixel > 0:

        draw.rectangle(
            (
                slider_x + 1,
                slider_y + 1,
                slider_x + slider_pixel,
                slider_y + slider_height - 1
            ),
            outline=255,
            fill=255
        )

    # Send framebuffer to SSD1306.
    display.image(image)
    display.show()


# ============================================================
# OSC: TEXT
# ============================================================

def receive_text(value):

    global text_message
    global scroll_position
    global last_scroll_time

    text_message = str(value)

    scroll_position = 0
    last_scroll_time = time.monotonic()

    print("TEXT:", text_message)

    update_display()


# ============================================================
# OSC: SLIDER
# ============================================================

def receive_slider(value):

    global slider_value

    try:
        value = float(value)
    except (TypeError, ValueError):
        return

    # Keep the original OSC value in the range 0...1.
    slider_value = max(0.0, min(1.0, value))

    # Deliberately don't print anything here.
    #
    # The main loop will decide whether the value has moved
    # far enough to change an OLED pixel.


# ============================================================
# TEXT SCROLLING
# ============================================================

def update_scroll():

    global scroll_position
    global last_scroll_time

    if len(text_message) <= MAX_TEXT_CHARS:
        return

    now = time.monotonic()

    if now - last_scroll_time >= SCROLL_INTERVAL:

        scroll_position += 1

        cycle_length = len(text_message) + 5

        if scroll_position >= cycle_length:
            scroll_position = 0

        last_scroll_time = now

        update_display()


# ============================================================
# OSC SETUP
# ============================================================

def setup_osc():

    print("Starting OSC...")

    osc_startup()

    # IMPORTANT:
    #
    # Your installed osc4py3 version uses:
    #
    # osc_udp_server(address, port, name)

    osc_udp_server(
        OSC_HOST,
        OSC_PORT,
        "pd_input"
    )

    osc_method(
        TEXT_ADDRESS,
        receive_text
    )

    osc_method(
        SLIDER_ADDRESS,
        receive_slider
    )

    print("OSC server running.")
    print("Address:", OSC_HOST)
    print("Port:", OSC_PORT)
    print()


# ============================================================
# MAIN
# ============================================================

def main():

    global last_slider_pixel

    setup_osc()

    print("Waiting for Pure Data...")
    print("Press Ctrl+C to quit.")
    print()

    # Initial display.
    update_display()

    try:

        while True:

            # Receive/process OSC packets.
            osc_process()

            # Calculate visible slider position.
            new_slider_pixel = round(
                slider_value * 122
            )

            # Only update OLED if a physical pixel changed.
            if new_slider_pixel != last_slider_pixel:
                update_display()

            # Text scrolling.
            update_scroll()

            # Keep OSC responsive without using 100% CPU.
            time.sleep(LOOP_SLEEP)

    except KeyboardInterrupt:

        print()
        print("Stopping...")

    finally:

        display.fill(0)
        display.show()

        osc_terminate()

        print("OSC stopped.")
        print("OLED cleared.")


# ============================================================
# START
# ============================================================

if __name__ == "__main__":
    main()
